# Should file, even if environment is sourced, if lowercase project is undefined
# source in bash by
# . example/environment
---
- name: '{{ env "project" }} Pre Process Playbook'
  hosts: {{ env "HOSTS" }}
  # vars:
  tasks:
  - name: echo
    shell: echo {{ env "TEXT" }}